<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Demo integral de bonos</title>
<style>body{margin:0;background:#eef5f3;color:#16313c;font-family:Inter,system-ui,sans-serif}.wrap{max-width:1320px;margin:auto;padding:28px}.hero,.panel{background:#fff;border-radius:22px;padding:24px;box-shadow:0 12px 35px #173b4b12;margin-bottom:20px}.eyebrow{color:#008b74;font-weight:800;letter-spacing:.18em;font-size:12px}.hero h1{margin:.35rem 0;font-size:clamp(26px,4vw,42px)}.steps,.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.step,.stat{padding:14px;border-radius:14px;background:#f1f7f6;border:1px solid #dceae7}.step b,.stat b{display:block;color:#087b68;font-size:19px}.panel h2{margin-top:0}.tablebox{overflow:auto}table{width:100%;border-collapse:collapse;min-width:960px}th,td{text-align:left;padding:12px;border-bottom:1px solid #e1e9e8;vertical-align:top}th{font-size:12px;text-transform:uppercase;color:#587078}.badge{display:inline-block;border-radius:999px;padding:5px 9px;background:#e4f4ee;color:#087555;font-weight:700}.empty{padding:28px;text-align:center;color:#64777d}.hint{color:#64777d}.actions a{display:inline-block;margin:.2rem;padding:.45rem .7rem;border-radius:10px;background:#087b68;color:white;text-decoration:none}@media(max-width:900px){.steps,.stats{grid-template-columns:repeat(2,1fr)}}</style></head><body>
@include('partials.demo_user_switcher')
<style>.demo-login{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:18px 0}.demo-login form{margin:0}.demo-login button{border:0;border-radius:12px;padding:12px 18px;background:#1848a1;color:#fff;font-weight:900;cursor:pointer}.demo-credential{padding:9px 12px;border-radius:10px;background:#edf4ff;color:#1848a1;font-weight:800}</style>
<main class="wrap">
<section class="hero"><div class="eyebrow">SISTEMA DE BONOS · DEMOSTRACIÓN AUTOCONTENIDA</div><h1>Compra, atención, auditoría y depósito</h1><p class="hint">Use la barra superior para cambiar de perfil sin cerrar sesión. Cada acción actualiza la misma trazabilidad y aparece aquí.</p>
<div class="demo-login"><form method="POST" action="{{ route('demo.login-bono') }}">@csrf<button type="submit">Ingresar como paciente demo</button></form><span class="demo-credential">Usuario: demo-bono · Clave de referencia: 123</span><small class="hint">La demo autentica automáticamente y no solicita la clave.</small></div>
<div class="steps">@foreach(['1. Compra','2. Recepción','3. Espera','4. Atención','5. Auditoría','6. Depósito'] as $paso)<div class="step"><b>{{ $paso }}</b></div>@endforeach</div></section>
<section class="stats">@foreach($resumen as $nombre => $valor)<div class="stat"><b>{{ $valor }}</b>{{ str_replace('_',' ',ucfirst($nombre)) }}</div>@endforeach</section>
<section class="panel"><h2>Panel de administración del flujo</h2><div class="tablebox"><table><thead><tr><th>Bono</th><th>Paciente / profesional</th><th>Compra</th><th>Recepción y atención</th><th>Cobro / auditoría</th><th>Pago</th><th>Acciones</th></tr></thead><tbody>
@forelse($vouchers as $voucher)
@php($cobro=$voucher->cobros->sortByDesc('id')->first())
<tr><td><strong>{{ $voucher->codigo }}</strong><br><span class="badge">{{ $voucher->estado }}</span></td><td>{{ $voucher->beneficiario_nombre ?: $voucher->cliente_nombre }}<br><small>{{ $voucher->prestador_nombre }}</small></td><td>{{ optional($voucher->created_at)->format('d-m-Y H:i') }}<br>${{ number_format($voucher->valor_total ?: $voucher->valor,0,',','.') }}</td><td>Agenda: {{ $voucher->agenda?->estado ?? 'pendiente' }}<br>Atención: {{ $voucher->atencion_cerrada_at ? 'cerrada' : ($voucher->atencion_id ? 'iniciada' : 'pendiente') }}</td><td>{{ $cobro?->estado ?? 'pendiente de envío' }}<br><small>{{ $cobro?->auditado_at ? 'Auditado '.$cobro->auditado_at->format('d-m-Y H:i') : 'Sin resolución' }}</small></td><td>{{ $cobro?->pago_estado ?? 'pendiente' }}<br><small>{{ $cobro?->deposito_comprobante }}</small></td><td class="actions"><a href="{{ route('vouchers.qr',$voucher->qr_token) }}">Ver QR</a><a href="{{ route('vouchers.qr.lectorDemo',$voucher->qr_token) }}">Lector simulado</a></td></tr>
@empty<tr><td colspan="7" class="empty">Aún no hay bonos. Cambie a Paciente y realice la primera compra.</td></tr>@endforelse
</tbody></table></div></section>
</main></body></html>
